#!/usr/bin/env php
<?php

use Emsifa\Graphit\CLI\App;

$vendorDirs = [
    __DIR__.'/../../',
    __DIR__.'/vendor',
];

foreach ($vendorDirs as $vendorDir) {
    if (is_file($vendorDir.'/autoload.php')) {
        define('VENDOR_DIR', $vendorDir);
    }
}

if (!defined('VENDOR_DIR')) {
    throw new Exception("We cannot find vendor directory in this project.");
}

require_once(VENDOR_DIR.'/autoload.php');

$app = new App($argv);

$app->run();